homepage_settings:
  countdown:
    show: false
    timezone: US/NYC
    deadline: 2024-10-14 12:00
  modal:
    show: false
    delay: 5000
  testimonials:
    show: false
    title: "Testimonials"
  gallery:
    show: false
    title: "Code BEAM Lite NYC 2024"