---
trainings:
- training: _trainings/architecting-reactive-systems-for-scalability-and-reliability.md
  start: 2024-11-14 09:00:00
  end: 2024-11-14 17:00:00
  timezone: EST

# Below values need to be written down manually according to 
# event specific timezone and dates
# timezone - timezone of the event e.g. EST
# start - start date and time of the event !!! time in 24-hour format !!!
# end - end date and time of the event !!! time in 24-hour format !!!